version: '2'
services:
  machinelearning:
    image: nhatthai/machine-learning-python3.6
    container_name: machinelearning
    command: python3 /code/Natural_Language_Processing/natural_language_processing.py

    ports:
      - "9909:9909"
    volumes:
      - ../code:/code