version: '2'
services:
  machinelearning:
    container_name: machinelearning
    build:
      context: ./
    command: jupyter notebook
    ports:
      - "8888:8888"
    volumes:
      - ../code:/home/jovyan/work